title: Hans-Peter's Links
description: Personal link database by Hans-Peter Störr
show_downloads: false
google_analytics: G-56KJJ5NX2Y
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

# https://github.com/pages-themes/architect
